config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#new'

  get '/auth/headquarters/callback' => 'sessions#create_from_omniauth', as: :headquarters_callback
  delete '/sign_out' => 'sessions#destroy', as: :sign_out

  resources :links, only: [:create, :show, :index]
  post '/slack_hook' => 'slack_messages#create'
  get '/:id' => 'links#show'
end

app/models/link.rb
class Link < ActiveRecord::Base
end

app/models/user.rb
class User
  attr_reader :name, :email, :token

  def initialize(user_data = {}, token = nil)
    @user_data = user_data
    @name = user_data['name']
    @email = user_data['email']
    @token = token
  end

  def signed_in?
    token.present?
  end

  class Store
    class_attribute :users

    def self.add(user)
      self.users ||= {}
      self.users[user.token] = user
    end

    def self.fetch(token)
      (self.users && self.users[token]) || User.new
    end

    def self.remove(token)
      self.users ||= {}
      self.users.delete(token)
    end
  end

  private

  attr_reader :user_data
end

app/controllers/application_controller.rb
require 'trailblazer/operation/controller'

class ApplicationController < ActionController::Base
  include Trailblazer::Operation::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :require_login

  def current_user
    @current_user ||= User::Store.fetch(cookies[:auth_token])
  end
  helper_method :current_user

  def require_login
    unless current_user.signed_in?
      deny_access
    end
  end

  def deny_access
    respond_to do |format|
      format.any(:js, :json, :xml) { head :unauthorized }
      format.any { redirect_to root_path }
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  skip_before_action :require_login, only: :show

  def index
    form Link::Create
    @links = Link::Index.(link_params)
  end

  def create
    run Link::Create, link_params do |op|
      @new_link = op.model
    end

    @links = Link::Index.(link_params)
    render :index
  end

  def show
    run Link::Show, params.merge(user_agent: request.user_agent) do |op|
      return redirect_to op.model.url, :status => :moved_permanently
    end

    redirect_to '/', error: 'Invalid link'
  end

  private

  def link_params
    params.merge(user_email: current_user.email)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, except: :destroy

  def new
    if current_user.signed_in?
      redirect_to links_path
      return
    else
      render :new, layout: 'simple'
    end
  end

  def create_from_omniauth
    headquarters_user(auth_hash.info.email)
    redirect_to links_path
  end

  def destroy
    User::Store.delete cookies[:auth_token]
    cookies[:auth_token] = nil
    redirect_to root_path
  end

  private

  def headquarters_user(email)
    user_data = Headquarters::Client::Members.new(
      client_id: ENV['HQ_APP_ID'],
      client_secret: ENV['HQ_APP_SECRET']
    ).search(email).first
    return unless user_data

    cookies[:auth_token] = params[:code]
    user = User.new user_data, params[:code]
    User::Store.add user
  end

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/slack_messages_controller.rb
class SlackMessagesController < ApplicationController
  protect_from_forgery with: :null_session
  skip_before_action :require_login

  def create
    if params[:token] !=  ENV['SLACK_TOKEN']
      head 401
      return
    end

    url = clean_slack_formatting(params[:text][params[:trigger_word].size..-1])
    link_params = {
      link: {
        url: url,
        description: 'From Slack'
      },
      user_email: params[:user_name]
    }

    run Link::Create, link_params do |op|
      @new_link = op.model
      render json: { text: "#{root_url}#{@new_link.unique_key}" }
      return
    end

    render json: { text: "Sorry #{params[:user_name]}, could not create a link for you." }
  end

  private

  def clean_slack_formatting(url)
    if url =~ /\s?<([^|>]+)/
      $1
    else
      url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.slim
doctype html
html
head
  title LinkManager
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

body
  .Layout
    = link_to "Sign out", sign_out_path, method: :delete, class: 'Layout-session-actions'

    = yield

app/views/layouts/simple.slim
doctype html
html
head
  title LinkManager
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

body
  .Layout.Layout--centered
    = yield

app/views/links/index.slim
h1 Group Buddies Link Manager

= simple_form_for @form, html: { class: "Form" } do |form|
  = form.input :url,
    input_html: { class: "Input", required: true },
    wrapper_html: { class: "Form-inlineInput" }
  = form.input :description,
    input_html: { class: "Input", required: true },
    wrapper_html: { class: "Form-inlineInput" }
  = form.submit class: "Form-action"

.Layout-divider

- if @new_link
  p
    | Your shortened URL is:&nbsp;
    = raw concept 'link/created_link_cell', @new_link

.Layout-divider

- if @links.empty?
  p You haven't shared links yet
- else
  table.Table
    colgroup
      col width=30
      col width=30
      col width=30
      col width=10
    thead
      tr
        th Long URL
        th Created
        th Short URL
        th Clicks
    tbody
      - @links.each do |link|
        tr
          td.Table-cell = link_to link.url, link.url
          td.Table-cell = link.created_at
          td.Table-cell = raw concept 'link/created_link_cell', link
          td.Table-cell.Table-centeredCell = link.use_count